* Basic Structure
  An Org file at its core is a heirarchy of headings. Much like a research paper.
  There are headings and subheadings. These headings all start with stars.
  The number of stars denotes the level in the org file.

  To facilitate this, OrgExtended has multiple syntax scopes to allow each heading to be highlighted differently.

  Org files can look kind of frumpy if you color all the stars the same:
  #+begin_example
  orgmode.preamble 
  * Heading 1
  ** Heading 2
  *** Heading 3
  **** Heading 4
  #+end_example

  In Emacs, many org mode configurations use different fonts, unicode string replacement and variable indenting tricks to
  make the file look very pretty. Many of those features are not possible in this plugin.

  That said, we offer a orgmode.preamble that matches the leading stars, allowing us to color them the same as the background and thus
  give a semblance of indenting to our file:

  #+begin_example
  orgmode.preamble 
  * Heading 1
   * Heading 2
    * Heading 3
     * Heading 4
  #+end_example

  If that was it, Org would not be a very powerful format. That said org offers a plethora of extensions and tools for working with this heirarchy that make
  this format truly flexible and unique.

* TODO Todos

  Built into orgmode is the concept of todo lists.
  Org headings can have a state identifier that can flow through various states.

  #+BEGIN_EXAMPLE
   ,-> (unmarked) -> TODO -> DONE --.
   '--------------------------------' 
  #+END_EXAMPLE

  [[https://orgmode.org/manual/TODO-Basics.html#TODO-Basics][Org Mode Todo]]

  These todos can be used to create projects with sub tasks. In turn these todos can be
  listed and filtered or scheduled to appear in the org agenda.

  This in turn makes org mode a flexible and full features personal information manager.
  Tools like:

  - OrgTodoChange :: Lets you dynamically change the todo state of a heading.
  

  